name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libsasl2-dev
    - uses: niden/actions-memcached@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.9
        bundle install
        bundle exec rake
